# Generated by Django 4.2.7 on 2025-05-02 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Supplier Order',
                'verbose_name_plural': 'Supplier Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.order',),
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='store.supplier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Profile',
                'verbose_name_plural': 'Supplier Profiles',
            },
        ),
        migrations.CreateModel(
            name='DeliveryNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('delivery_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notification', to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('on_time_deliveries', models.IntegerField(default=0)),
                ('late_deliveries', models.IntegerField(default=0)),
                ('quality_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='store.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'period_start', 'period_end')},
            },
        ),
    ]
