# Generated by Django 5.1.2 on 2025-03-19 22:06

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierExtended',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.supplier',),
        ),
    ]
