# Generated by Django 4.2 on 2025-03-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierExtended',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.supplier',),
        ),
    ]
